name: Container Apps

on:
  push:
    branches: [ "deploy", "master" ]

env:
    AZURE_CONTAINER_REGISTRY: containerappimages
    CONTAINER_APP_NAME: containerapp
    RESOURCE_GROUP: container
    LOCATION: eastus2

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v3

    # - name: Validate build configuration (local test)
    #   uses: docker/build-push-action@v6
    #   with:
    #       context: .
    #       file: ./Dockerfile
    #       call: check

    # - name: Build Docker image (local test)
    #   run: |
    #       docker build -t containerapp:stage .

    # - name: Run container (local test)
    #   run: |
    #       docker run -d -p 8501:8501 --name localtest containerapp:stage
    #       sleep 10

    # - name: Test app (local test)
    #   run: |
    #       status=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8501)
    #       if [ "$status" -ne 200 ]; then
    #           echo "Health check failed! Expected HTTP 200. Got $status"
    #           exit 1
    #       else
    #           echo "Status $status"
    #       fi

    # - name: Clean container (local test)
    #   run: |
    #       docker stop localtest
    #       docker rm localtest

    - name: Log in to Azure
      uses: azure/login@v2
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Ensure ACR exists (create if missing)
      uses: azure/cli@v2
      with:
          inlineScript: |
              az account list -o table
              echo "Checking if ACR $ACR_NAME exists..."
              if ! az acr show --name ${{ env.AZURE_CONTAINER_REGISTRY }} --resource-group ${{ env.RESOURCE_GROUP }} &>/dev/null; then
                  echo "ACR not found. Creating..."
                  az acr create --name ${{ env.AZURE_CONTAINER_REGISTRY }} --resource-group ${{ env.RESOURCE_GROUP }} --sku Basic --location ${{ env.LOCATION }}
              else
                  echo "ACR already exists."
              fi

    - name: Log in to ACR
      uses: docker/login-action@v3
      with:
          registry: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

    # - name: Build and push container image to ACR
    #   uses: docker/build-push-action@v6
    #   with:
    #       push: true
    #       tags: |
    #           ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
    #           ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:latest
    #       file: ./Dockerfile

    # - name: Azure Login
    #   uses: azure/login@v2
    #   with:
    #       creds: ${{ secrets.AZURE_CREDENTIALS }}

    # - name: Deploy to Azure Container Apps
    #   uses: azure/container-apps-deploy-action@v1
    #   with:
    #     imageToDeploy: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
    #     resourceGroup:  ${{ env.RESOURCE_GROUP }}
    #     containerAppName: ${{ env.CONTAINER_APP_NAME }}
    #     registryUrl: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
    #     registryUsername: ${{ secrets.AZURE_REGISTRY_USERNAME }}
    #     registryPassword: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
    #     environmentVariables: "DB_USER=${{ secrets.DB_USER }} DB_PORT=${{ secrets.DB_PORT }} DB_PASSWORD=${{ secrets.DB_PASSWORD }} DB_NAME=${{ secrets.DB_NAME }} DB_HOST=${{ secrets.DB_HOST }}"
              
