name: Container Apps

on:
  push:
    branches: [ "deploy", "master" ]

env:
    AZURE_CONTAINER_REGISTRY: containerappimages5
    CONTAINER_APP_NAME: containerapp5
    RESOURCE_GROUP: container
    LOCATION: eastus2
    PORT: 8501

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v3

    # - name: Validate build configuration (local test)
    #   uses: docker/build-push-action@v6
    #   with:
    #       context: .
    #       file: ./Dockerfile
    #       call: check

    # - name: Build Docker image (local test)
    #   run: |
    #       docker build -t containerapp:stage .

    # - name: Run container (local test)
    #   run: |
    #       docker run -d -p 8501:8501 --name localtest containerapp:stage
    #       sleep 10

    # - name: Test app (local test)
    #   run: |
    #       status=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8501)
    #       if [ "$status" -ne 200 ]; then
    #           echo "Health check failed! Expected HTTP 200. Got $status"
    #           exit 1
    #       else
    #           echo "Status $status"
    #       fi

    # - name: Clean container (local test)
    #   run: |
    #       docker stop localtest
    #       docker rm localtest

    - name: Log in to Azure
      uses: azure/login@v2
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Ensure ACR exists (create if missing)
      uses: azure/cli@v2
      with:
          inlineScript: |
              echo "Checking if ${{ env.AZURE_CONTAINER_REGISTRY }} exists..."
              if ! az acr show --name ${{ env.AZURE_CONTAINER_REGISTRY }} --resource-group ${{ env.RESOURCE_GROUP }} &>/dev/null; then
                  echo "ACR not found. Creating..."
                  az acr create --name ${{ env.AZURE_CONTAINER_REGISTRY }} --resource-group ${{ env.RESOURCE_GROUP }} --sku Basic --location ${{ env.LOCATION }}
              else
                  echo "ACR ${{ env.AZURE_CONTAINER_REGISTRY }} already exists."
              fi

    - name: Log in to ACR (Before Deploy)
      run: |
          az acr login --name ${{ env.AZURE_CONTAINER_REGISTRY }}

          repo_table=$(az acr repository list --name ${{ env.AZURE_CONTAINER_REGISTRY }} --output table)
          echo "$repo_table"

          if echo "$repo_table" | grep -wq "${{ env.CONTAINER_APP_NAME }}"; then
              echo "Repository found: ${{ env.CONTAINER_APP_NAME }}"
              az acr repository show-tags \
                --name "${{ env.AZURE_CONTAINER_REGISTRY }}" \
                --repository "${{ env.CONTAINER_APP_NAME }}" \
                --output table
          else
              echo "Repository not found or no images available."
          fi

    - name: Build and push container image to ACR
      uses: docker/build-push-action@v6
      with:
          push: true
          tags: |
              ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
              ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:latest
          file: ./Dockerfile

    - name: Log in to ACR (After Deploy)
      run: |
          az acr login --name ${{ env.AZURE_CONTAINER_REGISTRY }}
          az acr repository list --name ${{ env.AZURE_CONTAINER_REGISTRY }} --output table
          az acr repository show-tags --name ${{ env.AZURE_CONTAINER_REGISTRY }} --repository ${{ env.CONTAINER_APP_NAME }} --output table

    - name: Evaluating ContainerApps
      run: |
          containerapps=$(az containerapp env list --resource-group container --output table)
          echo "$containerapps"

          if echo "$containerapps" | grep -wq "${{ env.CONTAINER_APP_NAME }}"; then
              echo "Container exists: ${{ env.CONTAINER_APP_NAME }}"
          else
              echo "Container does not exist"
              az containerapp env create --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --location ${{ env.LOCATION }}
          fi

          az containerapp create \
              --name ${{ env.CONTAINER_APP_NAME }} \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --environment ${{ env.CONTAINER_APP_NAME }} \
              --image mcr.microsoft.com/azuredocs/containerapps-helloworld:latest \
              --target-port 80 \
              --ingress external \
              --registry-identity system \
              --query properties.configuration.ingress.fqdn \
              --output tsv

            az role assignment create \
              --assignee $(az containerapp identity show \
                --name ${{ env.CONTAINER_APP_NAME }} \
                --resource-group ${{ env.RESOURCE_GROUP }} \
                --query principalId -o tsv) \
              --role acrpull \
              --scope $(az acr show \
                --name ${{ env.AZURE_CONTAINER_REGISTRY }} \
                --resource-group ${{ env.RESOURCE_GROUP }} \
                --query id -o tsv)

            az containerapp update \
              --name ${{ env.CONTAINER_APP_NAME }} \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }} \
              --target-port ${{ env.PORT }} \
              --registry-server ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io \
              --env-vars \
                    DB_USER=${{ secrets.DB_USER }}\
                    DB_PORT=${{ secrets.DB_PORT }}\
                    DB_PASSWORD=${{ secrets.DB_PASSWORD }}\
                    DB_NAME=${{ secrets.DB_NAME }}\
                    DB_HOST=${{ secrets.DB_HOST }}
              --query properties.configuration.ingress.fqdn \
              --output tsv

    # - name: Deploy to Azure Container Apps
    #   uses: azure/container-apps-deploy-action@v1
    #   with:
    #     imageToDeploy: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
    #     resourceGroup:  ${{ env.RESOURCE_GROUP }}
    #     containerAppName: ${{ env.CONTAINER_APP_NAME }}
    #     registryUrl: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
    #     registryUsername: ${{ secrets.AZURE_REGISTRY_USERNAME }}
    #     registryPassword: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
    #     environmentVariables: "DB_USER=${{ secrets.DB_USER }} DB_PORT=${{ secrets.DB_PORT }} DB_PASSWORD=${{ secrets.DB_PASSWORD }} DB_NAME=${{ secrets.DB_NAME }} DB_HOST=${{ secrets.DB_HOST }}"
              
